### PR TITLE
Manage errors

### PR DESCRIPTION
**Pull request by dechuck**
The gem do not manage errors properly.
Now, if the API return an error, the class will raise an exception.

The dev who will use the gem, will need to catch the error.

### CODE REVIEW

**Comment by lukechesser** [comment]
@aaronklaassen can you look over when you get a chance?

**Comment by aaronklaassen** [comment]
Yep good improvement. :+1:

**Comment by lukechesser** [comment]
Cool I'll merge and give you guys access to RubyGems to push new changes

**Comment by lukechesser** [comment]
@dechuck you want to update the RubyGems version and push it?

This closes #3 right?

**Pull request merged**
